-- AlterTable
ALTER TABLE `RouterSession` ADD COLUMN `duration` INTEGER NULL,
    ADD COLUMN `ipAddress` VARCHAR(191) NULL,
    ADD COLUMN `loginTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `logoutTime` DATETIME(3) NULL,
    ADD COLUMN `macAddress` VARCHAR(191) NULL;
